import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr" className="h-full antialiased">

			<body className={`${geistSans.className} bg-daisy-bg text-daisy-text flex justify-center min-h-screen`}>
				
				<div className="bg-white w-full max-w-[414px] min-h-screen shadow-2xl flex flex-col relative overflow-hidden">
					{children}
				</div>
				
			</body>
		</html>
	);
}